cache:
  key: frontend-${CI_COMMIT_REF_NAME}
  paths:
    - node_modules/

variables:
  CI: "true"

stages:
  - dep
  - test
  - docs
  - build
  - deploy

install_mod:
  stage: dep
  image: node:10.15.3
  tags:
    - misakey_js
  script:
    - make dep

lint_code:
  stage: test
  image: node:10.15.3
  tags:
    - misakey_js
  before_script:
    - make dep
  script:
    - make strict-lint
  only:
    refs:
      - tags
      - branches
      - schedules
      - web
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^wip:/


unit_tests:
  stage: test
  image: node:10.15.3
  tags:
    - misakey_js
  before_script:
    - make dep
  script:
    - make test
  only:
    refs:
      - tags
      - branches
      - schedules
      - web
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^wip:/

docs:
  stage: docs
  image: node:10.15.3
  tags:
    - misakey_js
  before_script:
    - make dep
  script:
    - make docs
  artifacts:
    paths:
      - styleguide

build:
  stage: build
  image: docker:stable
  tags:
    - misakey_docker
  before_script:
    - apk add make
    - apk add git
    - make docker-login
  script:
    - make build
    - make deploy
  only:
    refs:
      - master
      - tags
      - schedules
      - web
      - branches
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^wip:/

include:
  - .gitlab-ci.packages.yml

pages:
  stage: deploy
  tags:
    - misakey_js
  script:
    - mv public public_unpublished
    - cp -r styleguide public
  artifacts:
    paths:
      - public
  only:
    refs:
      - master
    changes:
      - src/packages/*