cache:
  key: frontend-${CI_COMMIT_REF_NAME}
  untracked: true
  paths:
    - node_modules/
  policy: pull

variables:
  CI: "true"

stages:
  - dep
  - test
  - docs
  - build
  - deploy

install_mod:
  stage: dep
  image: node:10.15.3
  tags:
    - misakey_js
  script:
    - make dep
  cache:
    key: frontend-${CI_COMMIT_REF_NAME}
    untracked: true
    paths:
      - node_modules/
    policy: push
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^wip:/

lint_code:
  stage: test
  image: node:10.15.3
  tags:
    - misakey_js
  before_script:
    - make dep
  script:
    - make strict-lint
  only:
    refs:
      - tags
      - branches
      - schedules
      - web
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^wip:/


unit_tests:
  stage: test
  image: node:10.15.3
  tags:
    - misakey_js
  before_script:
    - make dep
  script:
    - make test
  only:
    refs:
      - tags
      - branches
      - schedules
      - web
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^wip:/

docs:
  stage: docs
  image: node:10.15.3
  tags:
    - misakey_js
  before_script:
    - make dep
  script:
    - make docs
  artifacts:
    paths:
      - styleguide
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^wip:/

build:
  stage: build
  image: docker:19.03.8 #Fixme: put back stable when gitlab is updated
  tags:
    - misakey_docker
  before_script:
    - apk add make
    - apk add git
    - make docker-login
  script:
    - make build
    - make deploy
  only:
    refs:
      - master
      - tags
      - schedules
      - web
      - branches
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^wip:/

build_maintenance:
  stage: build
  image: docker:19.03.8 #Fixme: put back stable when gitlab is updated
  tags:
    - misakey_docker
  before_script:
    - apk add make
    - apk add git
    - make docker-login
  script:
    - make build-maintenance
    - make deploy-maintenance
  only:
    refs:
      - master
    changes:
      - maintenance/*

include:
  - .gitlab-ci.packages.yml

pages:
  stage: deploy
  tags:
    - misakey_js
  script:
    - mv public public_unpublished
    - cp -r styleguide public
  artifacts:
    paths:
      - public
  only:
    refs:
      - master
    changes:
      - src/packages/ui/**/*
      - src/packages/auth/**/*
      - styleguide/**/*
      - styleguide.config.js