variables:
  CI: "true"

stages:
  - test
  - docs
  - build
  - deploy

lint_code:
  stage: test
  image: $CI_REGISTRY_IMAGE/base-image:latest
  tags:
    - misakey_js
  before_script:
    - ln -s /app/node_modules ./node_modules
  script:
    - make strict-lint
  only:
    refs:
      - tags
      - branches
      - schedules
      - web
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^wip:/

unit_tests:
  stage: test
  image: $CI_REGISTRY_IMAGE/base-image:latest
  tags:
    - misakey_js
  before_script:
    - ln -s /app/node_modules ./node_modules
  script:
    - make test
  only:
    refs:
      - tags
      - branches
      - schedules
      - web
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^wip:/

docs:
  stage: docs
  image: $CI_REGISTRY_IMAGE/base-image:latest
  tags:
    - misakey_js
  before_script:
    - ln -s /app/node_modules ./node_modules
  script:
    - make docs
  artifacts:
    paths:
      - styleguide
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^wip:/

build:
  stage: build
  image: docker:19.03.8 #Fixme: put back stable when gitlab is updated
  tags:
    - misakey_docker_front
  before_script:
    - apk add make
    - apk add git
    - make docker-login
  script:
    - make build
    - make deploy
  only:
    refs:
      - master
      - tags
      - schedules
      - web
      - branches
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^wip:/

build_maintenance:
  stage: build
  image: docker:19.03.8 #Fixme: put back stable when gitlab is updated
  tags:
    - misakey_docker_front
  before_script:
    - apk add make
    - apk add git
    - make docker-login
  script:
    - make build-maintenance
    - make deploy-maintenance
  only:
    refs:
      - master
    changes:
      - maintenance/*

pages:
  stage: deploy
  tags:
    - misakey_js
  script:
    - mv public public_unpublished
    - cp -r styleguide public
  artifacts:
    paths:
      - public
  only:
    refs:
      - master
    changes:
      - src/packages/ui/**/*
      - src/packages/auth/**/*
      - styleguide/**/*
      - styleguide.config.js
