cache:
  paths:
    - node_modules/

variables:
  CI: "true"


stages:
  - dep
  - test
  - build

install_mod:
  stage: dep
  image: node:10.15.3
  tags:
    - misakey_js
  script:
    - make dep

lint_code:
  stage: test
  image: node:10.15.3
  tags:
    - misakey_js
  script:
    - make dep
    - make strict-lint
  only:
    refs:
      - tags
      - branches
      - schedules
      - web
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^wip:/


unit_tests:
  stage: test
  image: node:10.15.3
  tags:
    - misakey_js
  script:
    - make dep
    - make test
  only:
    refs:
      - tags
      - branches
      - schedules
      - web
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^wip:/


build:
  stage: build
  image: docker:stable
  tags:
    - misakey_docker
  before_script:
    - apk add make
    - apk add git
    - make docker-login
  script:
    - make build
    - make tag
    - make deploy
  only:
    refs:
      - master
      - tags
      - schedules
      - web
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^wip:/
