{{- if .Values.ingressRoute.enabled -}}
{{- $fullName := include "frontend.fullname" . -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ template "frontend.fullname" . }}
  labels:
    app: {{ template "frontend.name" . }}
    chart: {{ template "frontend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.ingressRoute.domain }}`)
      services:
        - name: {{ $fullName }}
          port: {{ .Values.service.port }}
      middlewares:
        - name: web-headers
        - name: frontend-security-headers
  tls:
    certResolver: le
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: web-headers
spec:
  headers:
    contentSecurityPolicy: "{{ .Values.ingressRoute.contentSecurityPolicy }}"
    customFrameOptionsValue: "SAMEORIGIN"
    contentTypeNosniff: true
    featurePolicy: "autoplay 'none'; camera 'none'"
    customBrowserXssValue: "1; mode=block"
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: frontend-security-headers
spec:
  headers:
    frameDeny: true
    sslRedirect: true
    referrerPolicy: "origin"
    stsSeconds: 31536000
    stsIncludeSubdomains: true
    stsPreload: true
    forceSTSHeader: true
{{- end }}
