apiVersion: apps/v1
kind: Deployment
metadata:
  name: maintenance
  labels:
    app: maintenance
    chart: {{ template "frontend.chart" . }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maintenance
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: maintenance
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: maintenance
          image: "{{ .Values.image.repository }}/maintenance:master"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
