config: >-
  window.env = {
    ENV: 'preprod',
    API_ENDPOINT: 'https://api.preprod.misakey.dev',
    GAPI_CLIENT_ID: '932593622193-rgk9os4utgk93v2ac3k6bbrqu9v829l3.apps.googleusercontent.com',
    AUTH: {
      authority: 'https://auth.preprod.misakey.dev/_',
      client_id: 'f1f6c6c8-2b91-4a63-8797-cb0fffdcf3df',
      redirect_uri: 'https://api.preprod.misakey.dev/app/auth/callback',
    },
    SENTRY: {
      debug: false,
      dsn: 'https://a695e1e73b004ad2bc1f82b581f072fe@sentry.io/2071584',
      environment: 'preprod',
    },
    CATEGORIES: [
      'press',
      'bet'
    ],
    MATOMO: {
      URL: 'https://analytics.misakey.com/',
      SITE_ID: '4'
    },
    ACTIVE_SERVICES: [
      'mortdu.fun',
      't0nio.com',
      'cedricvanrompay.fr',
      'preprod.misakey.dev',
      'toupy.fr',
      'misadmin.preprod.misakey.dev',
      'twitter.com',
      'google.fr',
      'liberation.fr',
      'facebook.com',
      'lemonde.fr',
      'rdvsimple.com'
    ]
  };
    
  