env: production
config: >-
  window.env = {
    ENV: 'production',
    API_ENDPOINT: 'https://api.misakey.com',
    API_WS_ENDPOINT: 'wss://api.misakey.com',
    GAPI_CLIENT_ID: '932593622193-c6i3ghh44ip9hhbh2heempuugcbk94n7.apps.googleusercontent.com',
    SELF_CLIENT: {
      id: 'f27effe1-5d57-4b70-bf73-939feef50f71'
      name: 'Misakey',
      logoUri: 'https://static.misakey.com/ssoClientsLogo/misakey.png',
    },
    AUTH: {
      authority: 'https://auth.misakey.com/_',
      clientId: 'f27effe1-5d57-4b70-bf73-939feef50f71',
      redirectUri: 'https://api.misakey.com/auth/callback',
      enableAutomaticSilentRenew: true,
    },
    SENTRY: {
      debug: false,
      dsn: 'https://a695e1e73b004ad2bc1f82b581f072fe@sentry.io/2071584',
      environment: 'production',
    },
    MATOMO: {
      ENABLED: true,
      URL: 'https://analytics.misakey.com',
      SITEID: '1'
    },
  };
