# Default values for frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

maintenance: false

image:
  repository: misakey/frontend
  maintenanceRepository: misakey/frontend-maintenance
  tag:
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false

ingressRoute:
  enabled: true
  domain: app.misakey.com
  contentSecurityPolicy: "default-src 'self' https://*.misakey.com https://sentry.io; frame-src 'self' https://*.misakey.com https://misakey.typeform.com https://content.googleapis.com https://accounts.google.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.misakey.com https://embed.typeform.com https://apis.google.com; style-src 'self' 'unsafe-inline'; object-src 'none'; img-src data: https://*.misakey.com 'self';"

resources:
  limits:
   cpu: 100m
   memory: 64Mi
  requests:
   cpu: 100m
   memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}

config: 
